// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as wails$0 from "../../../../../example.com/marmot/internal/presentation/wails/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "cleanup-progress": wails$0.CleanupProgress;
            "node-menu": wails$0.NodeMenuAction;
            "scan-progress": wails$0.ScanProgress;
            "snapshot-updated": wails$0.LiveUpdate;
            "storage-sources-changed": void;
            "volume-menu": wails$0.VolumeMenuAction;
        }
    }
}
