// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChildrenQuery {
    "snapshotId": number;
    "parentId": number;
    "limit": number;
    "offset": number;
}

export interface ChildrenResult {
    "nodes": NodeView[] | null;
    "limit": number;
    "offset": number;
}

export interface CleanupItemResult {
    "path": string;
    "state": string;
    "reason": string;
}

export interface CleanupItemValidation {
    "path": string;
    "valid": boolean;
    "reason": string;
}

export interface CleanupPlan {
    "id": string;
    "snapshotId": number;
    "version": number;
    "state": string;
    "items": number;
    "results": CleanupItemResult[] | null;
}

export interface CleanupPlanRequest {
    "snapshotId": number;
    "paths": string[] | null;
}

export interface CleanupValidation {
    "planId": string;
    "version": number;
    "valid": boolean;
    "items": CleanupItemValidation[] | null;
}

export interface MapEntry {
    "kind": string;
    "node": NodeView;
    "name": string;
    "virtualType": string;
    "displayState": string;
    "capabilities": string[] | null;
    "count": number;
    "logicalSize": number;
    "allocatedSize": number;
    "ownedAllocated": number;
    "confidence": string;
    "sizeBasis": string;
    "children"?: ProjectedEntry[] | null;
    "childrenTotal"?: number;
    "childrenHasMore"?: boolean;
}

export interface MapQuery {
    "snapshotId": number;
    "parentId": number;
    "limit": number;
    "offset": number;
    "measure": string;
    "depth": number;
    "projectionLimit": number;
    "minSweeps": number[] | null;
}

export interface MapResult {
    "snapshotId": number;
    "snapshotVersion": number;
    "parent": NodeView;
    "entries": MapEntry[] | null;
    "total": number;
    "limit": number;
    "offset": number;
    "hasMore": boolean;
    "remaining": MapEntry;
    "confidence": string;
    "volumeTotalBytes": number;
    "volumeUsedBytes": number;
    "volumeFreeBytes": number;
    "densityTruncated": boolean;
}

export interface NodeActionResult {
    "ok": boolean;
    "code": string;
    "message": string;
    "path": string;
}

export interface NodeView {
    "id": number;
    "parentId": number;
    "path": string;
    "name": string;
    "kind": string;
    "logicalSize": number;
    "allocatedSize": number;
    "ownedAllocated": number;
    "volumeId": string;
    "confidence": string;
    "sizeBasis": string;
    "hasChildren": boolean;
}

export interface PermissionStatus {
    "platform": string;
    "state": string;
    "message": string;
}

/**
 * ProjectedEntry is one arc below the current level. It carries only what the
 * space map draws with; it has no path and no capabilities (ADR-0048).
 */
export interface ProjectedEntry {
    "id": number;
    "name": string;
    "kind": string;
    "size": number;
    "children"?: ProjectedEntry[] | null;
    "total"?: number;
    "more"?: boolean;
}

export interface ScanOptions {
    "root": string;
}

export interface ScanProgress {
    "taskId": string;
    "snapshotId": number;
    "root": string;
    "state": string;
    "phase": string;
    "nodes": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "issues": string[] | null;
    "error": string;
    "snapshotVersion": number;
    "affectedParentIds": number[] | null;

    /**
     * CountedBytes and VolumeUsedBytes are the progress bar's numerator and
     * denominator (ADR-0053 §1); Bytes stays the walked total.
     */
    "countedBytes": number;
    "volumeUsedBytes": number;
}

export interface ScanStatus {
    "taskId": string;
    "snapshotId": number;
    "root": string;
    "state": string;
    "phase": string;
    "nodes": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "issues": string[] | null;
    "error": string;

    /**
     * CountedBytes and VolumeUsedBytes are the progress bar's numerator and
     * denominator (ADR-0053 §1); Bytes stays the walked total.
     */
    "countedBytes": number;
    "volumeUsedBytes": number;
}

export interface StorageSourceOverview {
    "id": string;
    "name": string;
    "path": string;
    "kind": string;
    "totalBytes": number;
    "usedBytes": number;
    "freeBytes": number;
    "usageBasis": string;
    "permission": string;
    "message": string;
    "scannable": boolean;
    "members": StorageVolumeMember[] | null;
}

export interface StorageVolumeMember {
    "id": string;
    "name": string;
    "path": string;
    "kind": string;
    "role": string;
    "volumeTotalBytes": number;
    "volumeUsedBytes": number;
    "volumeFreeBytes": number;
    "usageBasis": string;
    "permission": string;
    "scannable": boolean;
}

/**
 * VolumeMenuAction is emitted when the user picks an item in a volume row's
 * native menu. The menu is only an input device: the frontend performs the
 * action with the service methods it already uses, so the business rules and the
 * error surface stay in one place (ADR-0051 §4).
 */
export interface VolumeMenuAction {
    "sourceId": string;
    "action": string;
}
