// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChildrenQuery {
    "snapshotId": number;
    "parentId": number;
    "limit": number;
    "offset": number;
}

export interface ChildrenResult {
    "nodes": NodeView[] | null;
    "limit": number;
    "offset": number;
}

export interface CleanupItemResult {
    "path": string;
    "state": string;
    "reason": string;
}

export interface CleanupItemValidation {
    "path": string;
    "valid": boolean;
    "reason": string;
}

export interface CleanupPlan {
    "id": string;
    "snapshotId": number;
    "version": number;
    "state": string;
    "items": number;
    "results": CleanupItemResult[] | null;
}

export interface CleanupPlanRequest {
    "snapshotId": number;
    "paths": string[] | null;
}

export interface CleanupValidation {
    "planId": string;
    "version": number;
    "valid": boolean;
    "items": CleanupItemValidation[] | null;
}

export interface MapEntry {
    "kind": string;
    "node": NodeView;
    "name": string;
    "count": number;
    "logicalSize": number;
    "allocatedSize": number;
    "ownedAllocated": number;
    "confidence": string;
    "sizeBasis": string;
}

export interface MapQuery {
    "snapshotId": number;
    "parentId": number;
    "limit": number;
    "offset": number;
    "measure": string;
}

export interface MapResult {
    "snapshotId": number;
    "snapshotVersion": number;
    "parent": NodeView;
    "entries": MapEntry[] | null;
    "total": number;
    "limit": number;
    "offset": number;
    "hasMore": boolean;
    "remaining": MapEntry;
    "confidence": string;
}

export interface NodeActionResult {
    "ok": boolean;
    "code": string;
    "message": string;
    "path": string;
}

export interface NodeView {
    "id": number;
    "parentId": number;
    "path": string;
    "name": string;
    "kind": string;
    "logicalSize": number;
    "allocatedSize": number;
    "ownedAllocated": number;
    "confidence": string;
    "sizeBasis": string;
    "hasChildren": boolean;
}

export interface PermissionStatus {
    "platform": string;
    "state": string;
    "message": string;
}

export interface ScanOptions {
    "root": string;
}

export interface ScanProgress {
    "taskId": string;
    "snapshotId": number;
    "root": string;
    "state": string;
    "phase": string;
    "nodes": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "issues": string[] | null;
    "error": string;
    "snapshotVersion": number;
    "affectedParentIds": number[] | null;
}

export interface ScanStatus {
    "taskId": string;
    "snapshotId": number;
    "root": string;
    "state": string;
    "phase": string;
    "nodes": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "issues": string[] | null;
    "error": string;
}

export interface VolumeOverview {
    "id": string;
    "name": string;
    "path": string;
    "kind": string;
    "totalBytes": number;
    "usedBytes": number;
    "freeBytes": number;
    "permission": string;
    "message": string;
    "scannable": boolean;
}
