// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChildrenQuery {
    "snapshotId": number;
    "parentId": number;
    "limit": number;
    "offset": number;
}

export interface ChildrenResult {
    "nodes": NodeView[] | null;
    "limit": number;
    "offset": number;
}

export interface CleanupItemResult {
    "path": string;
    "state": string;
    "reason": string;
}

export interface CleanupItemValidation {
    "path": string;
    "valid": boolean;
    "reason": string;
}

export interface CleanupPlan {
    "id": string;
    "snapshotId": number;
    "version": number;
    "state": string;
    "items": number;
    "results": CleanupItemResult[] | null;
}

export interface CleanupPlanRequest {
    "snapshotId": number;
    "paths": string[] | null;
}

export interface CleanupValidation {
    "planId": string;
    "version": number;
    "valid": boolean;
    "items": CleanupItemValidation[] | null;
}

export interface NodeView {
    "id": number;
    "parentId": number;
    "path": string;
    "name": string;
    "kind": string;
    "logicalSize": number;
    "allocatedSize": number;
    "ownedAllocated": number;
    "confidence": string;
    "sizeBasis": string;
    "hasChildren": boolean;
}

export interface PermissionStatus {
    "platform": string;
    "state": string;
    "message": string;
}

export interface ScanOptions {
    "root": string;
}

export interface ScanProgress {
    "taskId": string;
    "snapshotId": number;
    "root": string;
    "state": string;
    "nodes": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "issues": string[] | null;
    "error": string;
}

export interface ScanStatus {
    "taskId": string;
    "snapshotId": number;
    "root": string;
    "state": string;
    "nodes": number;
    "files": number;
    "directories": number;
    "bytes": number;
    "issues": string[] | null;
    "error": string;
}
