// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelScan(taskID: string): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(1079847515, taskID);
}

export function ConfirmCleanupPlan(planID: string, version: number): $CancellablePromise<$models.CleanupPlan> {
    return $Call.ByID(3725622731, planID, version);
}

export function CreateCleanupPlan(request: $models.CleanupPlanRequest): $CancellablePromise<$models.CleanupPlan> {
    return $Call.ByID(2832030583, request);
}

export function ExecuteCleanupPlan(planID: string, version: number): $CancellablePromise<$models.CleanupPlan> {
    return $Call.ByID(3364095130, planID, version);
}

export function GetChildren(query: $models.ChildrenQuery): $CancellablePromise<$models.ChildrenResult> {
    return $Call.ByID(3688422103, query);
}

export function GetMap(query: $models.MapQuery): $CancellablePromise<$models.MapResult> {
    return $Call.ByID(2827691950, query);
}

/**
 * GetNodeEntry is how the frontend collects an arc from a ring below the current
 * level: the projection it drew that arc from carries no path and no
 * capabilities, so the node has to be looked up by ID before anything may act on
 * it (ADR-0048).
 */
export function GetNodeEntry(snapshotID: number, nodeID: number): $CancellablePromise<$models.MapEntry> {
    return $Call.ByID(1974114536, snapshotID, nodeID);
}

export function GetPermissionStatus(): $CancellablePromise<$models.PermissionStatus> {
    return $Call.ByID(37670297);
}

export function GetScanStatus(taskID: string): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(173246179, taskID);
}

export function GetStorageSources(): $CancellablePromise<$models.StorageSourceOverview[] | null> {
    return $Call.ByID(106857813);
}

/**
 * PrepareVolumeMenu rebuilds the native menu for one volume row and returns the
 * name the frontend must trigger. It is rebuilt on every open so the item set
 * always matches the row it belongs to (ADR-0051 §3).
 */
export function PrepareVolumeMenu(sourceID: string, hasResult: boolean): $CancellablePromise<string> {
    return $Call.ByID(3520626822, sourceID, hasResult);
}

export function PreviewNode(snapshotID: number, nodeID: number): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(1900736820, snapshotID, nodeID);
}

export function RevealNode(snapshotID: number, nodeID: number): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(3842996745, snapshotID, nodeID);
}

/**
 * RevealStorageSource takes the source's identity, not a path: the path comes
 * from the volume catalog (ADR-0051 §5, DDD invariant 17).
 */
export function RevealStorageSource(sourceID: string): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(3892187735, sourceID);
}

export function StartScan(options: $models.ScanOptions): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(2776032857, options);
}

export function ValidateCleanupPlan(planID: string, version: number): $CancellablePromise<$models.CleanupValidation> {
    return $Call.ByID(4019481977, planID, version);
}
