// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelScan(taskID: string): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(1079847515, taskID);
}

export function ClearAdvisor(): $CancellablePromise<void> {
    return $Call.ByID(3874544543);
}

/**
 * ConfigureAdvisor stores the endpoint, model and key, encrypted in the app's
 * support directory. An empty apiKey keeps whatever is already stored, so
 * editing the endpoint does not require pasting the credential again.
 */
export function ConfigureAdvisor(settings: $models.AdvisorSettings, apiKey: string): $CancellablePromise<$models.AdvisorStatus> {
    return $Call.ByID(1599529864, settings, apiKey);
}

export function ConfirmCleanupPlan(planID: string, version: number): $CancellablePromise<$models.CleanupPlan> {
    return $Call.ByID(3725622731, planID, version);
}

export function CreateCleanupPlan(request: $models.CleanupPlanRequest): $CancellablePromise<$models.CleanupPlan> {
    return $Call.ByID(2832030583, request);
}

/**
 * DescribeNode is answered from the snapshot and the local catalog, so it is
 * cheap enough to ask while a pointer rests on a row.
 */
export function DescribeNode(snapshotID: number, nodeID: number): $CancellablePromise<$models.NodeDescription> {
    return $Call.ByID(1285871749, snapshotID, nodeID);
}

export function ExecuteCleanupPlan(planID: string, version: number): $CancellablePromise<$models.CleanupPlan> {
    return $Call.ByID(3364095130, planID, version);
}

export function GetAdvisorStatus(): $CancellablePromise<$models.AdvisorStatus> {
    return $Call.ByID(3888212314);
}

export function GetChildren(query: $models.ChildrenQuery): $CancellablePromise<$models.ChildrenResult> {
    return $Call.ByID(3688422103, query);
}

/**
 * GetCleanupAdvice is the rule layer alone, with no network request of any kind.
 */
export function GetCleanupAdvice(snapshotID: number): $CancellablePromise<$models.Advice> {
    return $Call.ByID(4091719120, snapshotID);
}

export function GetLiveUpdateStatus(): $CancellablePromise<$models.LiveUpdateStatus> {
    return $Call.ByID(407526245);
}

export function GetMap(query: $models.MapQuery): $CancellablePromise<$models.MapResult> {
    return $Call.ByID(2827691950, query);
}

/**
 * GetNodeEntry is how the frontend collects an arc from a ring below the current
 * level: the projection it drew that arc from carries no path and no
 * capabilities, so the node has to be looked up by ID before anything may act on
 * it (ADR-0048).
 */
export function GetNodeEntry(snapshotID: number, nodeID: number): $CancellablePromise<$models.MapEntry> {
    return $Call.ByID(1974114536, snapshotID, nodeID);
}

export function GetPermissionStatus(): $CancellablePromise<$models.PermissionStatus> {
    return $Call.ByID(37670297);
}

/**
 * GetReclaimable is asked for the selected set as a whole whenever the
 * selection changes; the badge shows its answer, not a sum of the rows.
 */
export function GetReclaimable(snapshotID: number, nodeIDs: number[] | null): $CancellablePromise<$models.ReclaimableSummary> {
    return $Call.ByID(191044847, snapshotID, nodeIDs);
}

export function GetScanStatus(taskID: string): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(173246179, taskID);
}

export function GetStorageSources(): $CancellablePromise<$models.StorageSourceOverview[] | null> {
    return $Call.ByID(106857813);
}

/**
 * OpenTerminalNode opens Terminal.app at the node's directory -- the node itself
 * when it is one, its parent otherwise. Same input shape as PreviewNode and
 * RevealNode: a snapshot and a node, never a path (ADR-0069 §5).
 */
export function OpenTerminalNode(snapshotID: number, nodeID: number): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(1725033928, snapshotID, nodeID);
}

/**
 * PrepareNodeMenu rebuilds the result page's node menu for one node and returns
 * the name the frontend must trigger. The accelerator label is the original's
 * hint and nothing more: a context menu's key equivalents only work while it is
 * open, and the real ⌘⌫ path stays in the frontend (R-071 §3).
 * 
 * No "预览" item: the original has one, but Quick Look from a menu was judged
 * useless in use (2026-09-09) -- Space on a focused row does the same with no
 * round trip. ADR-0069's revision note records the removal.
 */
export function PrepareNodeMenu(spec: $models.NodeMenuSpec): $CancellablePromise<string> {
    return $Call.ByID(2492691672, spec);
}

/**
 * PrepareVolumeMenu rebuilds the native menu for one volume row and returns the
 * name the frontend must trigger. It is rebuilt on every open so the item set
 * always matches the row it belongs to (ADR-0051 §3).
 */
export function PrepareVolumeMenu(sourceID: string, hasResult: boolean): $CancellablePromise<string> {
    return $Call.ByID(3520626822, sourceID, hasResult);
}

/**
 * PreviewEvidence renders exactly what an advisor would receive.
 */
export function PreviewEvidence(snapshotID: number): $CancellablePromise<$models.EvidencePreview> {
    return $Call.ByID(1628376013, snapshotID);
}

export function PreviewNode(snapshotID: number, nodeID: number): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(1900736820, snapshotID, nodeID);
}

/**
 * RereadDirectory re-reads one directory from disk and splices the result into
 * the current snapshot, keeping node IDs for unchanged objects. Same input shape
 * as the other node actions: a snapshot and a node, never a path (ADR-0070).
 */
export function RereadDirectory(snapshotID: number, nodeID: number): $CancellablePromise<$models.RereadResult> {
    return $Call.ByID(4215800016, snapshotID, nodeID);
}

export function RevealNode(snapshotID: number, nodeID: number): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(3842996745, snapshotID, nodeID);
}

/**
 * RevealStorageSource takes the source's identity, not a path: the path comes
 * from the volume catalog (ADR-0051 §5, DDD invariant 17).
 */
export function RevealStorageSource(sourceID: string): $CancellablePromise<$models.NodeActionResult> {
    return $Call.ByID(3892187735, sourceID);
}

/**
 * RunAdvisorAnalysis is the full flow: rule layer, then the advisor if one is
 * configured. The context is the frontend's -- cancelling the promise cancels
 * the request in flight rather than merely discarding its result.
 */
export function RunAdvisorAnalysis(snapshotID: number): $CancellablePromise<$models.Advice> {
    return $Call.ByID(1504811705, snapshotID);
}

/**
 * SetAdvisorEnabled flips the switch on a saved configuration without touching
 * the endpoint or the key. A failure to come back on is reported in the status's
 * Fault, next to the switch, rather than as an error.
 */
export function SetAdvisorEnabled(enabled: boolean): $CancellablePromise<$models.AdvisorStatus> {
    return $Call.ByID(2266906309, enabled);
}

export function StartScan(options: $models.ScanOptions): $CancellablePromise<$models.ScanStatus> {
    return $Call.ByID(2776032857, options);
}

export function ValidateCleanupPlan(planID: string, version: number): $CancellablePromise<$models.CleanupValidation> {
    return $Call.ByID(4019481977, planID, version);
}
